#!/usr/bin/python3 -tt

import sys,os,re

def find(pat,text):
	match = re.search(pat,text)
	if match:
		print(match.group())
	else:
		print("Not Found")
	
def main():
	find(sys.argv[1],sys.argv[2])



if __name__ == "__main__":
	main()
